// General knowledge for the crossword: what fills it out on a quiet week, when there
// aren't enough of your own answers yet. Friendly, gettable, British — a pub quiz, not
// a cryptic. Answers are letters only, three to nine of them.

export const GENERAL: [answer: string, clue: string][] = [
  ['TEA', 'Builder’s brew'],
  ['SCONE', 'Cream tea bake, however you say it'],
  ['CRUMPET', 'Holey teatime griddle cake'],
  ['BISCUIT', 'Something to dunk'],
  ['TOAST', 'Bread, browned — or a raised glass'],
  ['MARMITE', 'Love it or hate it'],
  ['BEANS', 'On toast, from a tin'],
  ['GRAVY', 'Poured over the Sunday roast'],
  ['CUSTARD', 'Yellow sauce for a crumble'],
  ['TRIFLE', 'Layered pudding with sherry'],
  ['PASTY', 'Cornish crimped snack'],
  ['CHIPS', 'Fish’s partner'],
  ['CURRY', 'Friday night takeaway, often'],
  ['KEBAB', 'Late-night meat on a skewer'],
  ['PIZZA', 'Margherita, for one'],
  ['PASTA', 'Penne or fusilli'],
  ['NOODLES', 'Slurped from a pot'],
  ['CHEESE', 'Cheddar or Stilton'],
  ['BUTTER', 'Spread on your crumpet'],
  ['HONEY', 'Bee’s sweet produce'],
  ['LEMON', 'Sour yellow fruit'],
  ['MANGO', 'Tropical stone fruit'],
  ['BANANA', 'Yellow fruit that’s peeled'],
  ['CHERRY', 'Fruit on top of a Bakewell'],
  ['GRAPE', 'Fruit for wine'],
  ['APPLE', 'A day keeps the doctor away'],
  ['ONION', 'Makes you cry when you chop it'],
  ['CARROT', 'Snowman’s nose'],
  ['POTATO', 'Mash or jacket'],
  ['PEAS', 'Mushy, with fish'],
  ['OMELETTE', 'Folded eggs'],
  ['PANCAKE', 'Tossed on Shrove Tuesday'],
  ['WAFFLE', 'Grid-patterned batter treat — or talk nonsense'],
  ['TOFFEE', 'Chewy sweet'],
  ['FUDGE', 'Soft sweet — or dodge the issue'],
  ['JELLY', 'Wobbly party pudding'],
  ['LATTE', 'Milky coffee'],
  ['COCOA', 'Bedtime hot drink'],
  ['CIDER', 'Apple drink from Somerset'],
  ['GIN', 'Juniper spirit, often with tonic'],
  ['PINT', 'Pub measure'],
  ['PUB', 'The local'],
  ['QUIZ', 'Tuesday night at the pub'],
  ['DARTS', 'Game of oche and bullseye'],
  ['SNOOKER', 'Cue sport with fifteen reds'],
  ['CRICKET', 'Game of overs and wickets'],
  ['TENNIS', 'Sport at Wimbledon'],
  ['RUGBY', 'Scrums and tries'],
  ['GOLF', 'Game with a hole in one'],
  ['GOAL', 'What a striker scores'],
  ['REFEREE', 'Official with a whistle'],
  ['MEDAL', 'Gold, silver or bronze'],
  ['TROPHY', 'Cup for the winners'],
  ['MARATHON', 'A run of 26.2 miles'],
  ['YOGA', 'Downward dog and friends'],
  ['SWIM', 'A few lengths of the pool'],
  ['BIKE', 'Two-wheeler'],
  ['KITE', 'Flown on a windy beach'],
  ['PICNIC', 'Meal on a blanket'],
  ['BEACH', 'Sand and sea'],
  ['PIER', 'Seaside walkway on stilts'],
  ['SEAGULL', 'Chip-stealing seaside bird'],
  ['SANDCASTLE', 'Built with bucket and spade'],
  ['WAVE', 'Surfer’s ride — or a hello'],
  ['TIDE', 'It comes in and goes out'],
  ['SHELL', 'Found on the shore'],
  ['CRAB', 'Sideways walker'],
  ['ISLAND', 'Land with sea all round'],
  ['HILL', 'Small mountain'],
  ['VALLEY', 'Low land between hills'],
  ['RIVER', 'The Thames, for one'],
  ['LAKE', 'Windermere, for one'],
  ['FOREST', 'Lots and lots of trees'],
  ['MEADOW', 'Grassy field of wildflowers'],
  ['GARDEN', 'Where the shed lives'],
  ['SHED', 'Garden hideaway'],
  ['LAWN', 'Mown on a Sunday'],
  ['ROSE', 'Red flower of romance'],
  ['DAISY', 'Flower for a chain'],
  ['TULIP', 'Dutch spring flower'],
  ['OAK', 'Tree from an acorn'],
  ['ACORN', 'Tiny nut, mighty tree'],
  ['ROBIN', 'Red-breasted Christmas card bird'],
  ['OWL', 'Night bird that hoots'],
  ['SWAN', 'Graceful white bird of the lake'],
  ['FOX', 'Urban bin-raider with a bushy tail'],
  ['BADGER', 'Black-and-white night digger'],
  ['HEDGEHOG', 'Prickly garden visitor'],
  ['SQUIRREL', 'Bushy-tailed nut hoarder'],
  ['RABBIT', 'Bunny'],
  ['PUPPY', 'Young dog'],
  ['KITTEN', 'Young cat'],
  ['PONY', 'Small horse'],
  ['SHEEP', 'Counted at bedtime'],
  ['COW', 'Moo-er'],
  ['PIG', 'Oinker'],
  ['DUCK', 'Quacker'],
  ['GOOSE', 'Honking bird — or a cheeky pinch'],
  ['BEE', 'Honey maker'],
  ['SPIDER', 'Eight-legged bath visitor'],
  ['TIGER', 'Striped big cat'],
  ['LION', 'King of the jungle'],
  ['ZEBRA', 'Striped horse of Africa'],
  ['GIRAFFE', 'Tallest animal'],
  ['PENGUIN', 'Bird that can’t fly but can swim'],
  ['DOLPHIN', 'Clever sea mammal'],
  ['WHALE', 'Largest animal of all'],
  ['SHARK', 'Fish with a famous fin'],
  ['OCTOPUS', 'Eight-armed sea creature'],
  ['DRAGON', 'Fire-breathing beast of legend'],
  ['UNICORN', 'Horse with a horn'],
  ['CASTLE', 'Home of a medieval king'],
  ['CROWN', 'Royal headwear'],
  ['QUEEN', 'Chess’s most powerful piece'],
  ['KNIGHT', 'Sir, in armour'],
  ['PIRATE', 'Sailor with a parrot'],
  ['TREASURE', 'X marks the spot'],
  ['ROBOT', 'Machine that does as it’s told'],
  ['ROCKET', 'Off to the moon'],
  ['PLANET', 'Mars, for one'],
  ['MOON', 'It has phases'],
  ['STAR', 'Twinkle, twinkle'],
  ['COMET', 'Space rock with a tail'],
  ['SUN', 'Centre of our solar system'],
  ['RAINBOW', 'Seven colours after rain'],
  ['CLOUD', 'Fluffy thing in the sky'],
  ['RAIN', 'British summer, often'],
  ['SNOW', 'Makes a white Christmas'],
  ['FOG', 'Pea-souper'],
  ['STORM', 'Thunder and lightning'],
  ['BREEZE', 'Gentle wind'],
  ['SUMMER', 'Season of long days'],
  ['WINTER', 'Coldest season'],
  ['AUTUMN', 'Season of falling leaves'],
  ['SPRING', 'Season of lambs and daffodils'],
  ['MONDAY', 'Start of the working week'],
  ['FRIDAY', 'End of the working week'],
  ['WEEKEND', 'Saturday and Sunday'],
  ['HOLIDAY', 'Time off, maybe abroad'],
  ['PASSPORT', 'Travel document'],
  ['SUITCASE', 'Packed for a trip'],
  ['AIRPORT', 'Gatwick or Heathrow'],
  ['TRAIN', 'Runs on rails'],
  ['BUS', 'Double-decker, in London'],
  ['TAXI', 'Black cab'],
  ['TUBE', 'London Underground'],
  ['BRIDGE', 'Crossing over a river'],
  ['LONDON', 'The Big Smoke'],
  ['PARIS', 'City of the Eiffel Tower'],
  ['ROME', 'Eternal City'],
  ['ITALY', 'Boot-shaped country'],
  ['SPAIN', 'Home of tapas'],
  ['FRANCE', 'Home of the croissant'],
  ['WALES', 'Land of the dragon flag'],
  ['SCOTLAND', 'Home of haggis and Hogmanay'],
  ['IRELAND', 'Emerald Isle'],
  ['CORNWALL', 'County of pasties and surf'],
  ['YORKSHIRE', 'County of puddings'],
  ['PIANO', 'Instrument with black and white keys'],
  ['GUITAR', 'Six-stringed instrument'],
  ['DRUMS', 'Kit that’s hit'],
  ['VIOLIN', 'Instrument played with a bow'],
  ['SONG', 'Something to sing'],
  ['DANCE', 'Move to the music'],
  ['DISCO', 'Night of the glitter ball'],
  ['KARAOKE', 'Singing along to the words on screen'],
  ['FILM', 'Seen at the cinema'],
  ['POPCORN', 'Cinema snack'],
  ['NOVEL', 'Book-length story'],
  ['POEM', 'Verse'],
  ['LIBRARY', 'Where books are borrowed'],
  ['CROSSWORD', 'This, for one'],
  ['PUZZLE', 'Jigsaw, for one'],
  ['JIGSAW', 'Puzzle of interlocking pieces'],
  ['CHESS', 'Game of checkmate'],
  ['CARDS', 'Deck of fifty-two'],
  ['DICE', 'Rolled in board games'],
  ['BALLOON', 'Party decoration full of air'],
  ['CANDLE', 'Blown out on a birthday cake'],
  ['CAKE', 'Birthday bake'],
  ['PARTY', 'Celebration with friends'],
  ['PRESENT', 'Gift — or the here and now'],
  ['WEDDING', 'Big day'],
  ['RING', 'Worn on the fourth finger'],
  ['BOUQUET', 'Bunch of flowers, thrown at a wedding'],
  ['KISS', 'X, at the end of a message'],
  ['HUG', 'Cuddle'],
  ['LOVE', 'All you need, say the Beatles'],
  ['HEART', 'Shape of love'],
  ['DATE', 'Night out for two — or a fruit'],
  ['SOFA', 'Settee'],
  ['DUVET', 'Quilt on the bed'],
  ['PILLOW', 'Head rest at night'],
  ['KETTLE', 'Boiled for a cuppa'],
  ['TOASTER', 'Pops up at breakfast'],
  ['FRIDGE', 'Keeps the milk cold'],
  ['OVEN', 'Where the roast goes'],
  ['TELLY', 'The box in the lounge'],
  ['REMOTE', 'Always lost down the sofa'],
  ['UMBRELLA', 'Brolly'],
  ['WELLIES', 'Rubber boots for puddles'],
  ['SCARF', 'Winter neck warmer'],
  ['JUMPER', 'Woolly top'],
  ['SLIPPERS', 'Cosy indoor shoes'],
  ['PYJAMAS', 'Worn to bed'],
  ['MIRROR', 'Glass for your reflection'],
  ['CLOCK', 'Tells the time'],
  ['ALARM', 'Wakes you up'],
  ['NAP', 'Forty winks'],
  ['DREAM', 'Night-time story in your head'],
  ['SMILE', 'Happy face'],
  ['LAUGH', 'Ha ha'],
  ['SECRET', 'Kept between the two of you'],
  ['TEAPOT', 'Pot for brewing a proper cuppa'],
  ['TOMATO', 'Red fruit that ends up in ketchup'],
  ['LETTUCE', 'Iceberg, for one'],
  ['PARSNIP', 'Pale root veg, roasted at Christmas'],
  ['RAISIN', 'Dried grape'],
  ['ORANGE', 'Colour and citrus fruit'],
  ['MELON', 'Honeydew, for one'],
  ['OLIVE', 'Green or black, often in a martini'],
  ['SALT', 'Shaken on chips with vinegar'],
  ['RISOTTO', 'Creamy Italian rice dish'],
  ['LASAGNE', 'Layered Italian pasta bake'],
  ['STEW', 'Slow-cooked one-pot dinner'],
  ['ROAST', 'Sunday dinner centrepiece'],
  ['TART', 'Bakewell, for one'],
  ['ECLAIR', 'Cream-filled choux bun'],
  ['SORBET', 'Fruity frozen dessert'],
  ['SALAD', 'Bowl of leaves'],
  ['CEREAL', 'Breakfast poured from a box'],
  ['STEAK', 'Rare, medium or well done'],
  ['SALMON', 'Pink fish, often smoked'],
  ['LOBSTER', 'Shellfish that turns red when cooked'],
  ['WINE', 'Red, white or rosé'],
  ['LAGER', 'Pale, fizzy pint'],
  ['ESPRESSO', 'Short, strong coffee'],
  ['TONIC', 'Mixer for gin'],
  ['SALSA', 'Latin dance — or a tomato dip'],
  ['TANGO', 'Dance it takes two to do'],
  ['BALLET', 'Dance in tutus'],
  ['OPERA', 'Drama that’s sung'],
  ['THEATRE', 'West End venue'],
  ['ACTOR', 'Performer on stage or screen'],
  ['ORCHESTRA', 'Players led by a conductor'],
  ['POET', 'Wordsworth, for one'],
  ['LETTER', 'A, B or C — or something the postman brings'],
  ['TEASPOON', 'Small one for stirring in the sugar'],
  ['PLATE', 'Dinner is served on it'],
  ['TOWEL', 'Dry off with it after a bath'],
  ['SOAP', 'Lather maker — or EastEnders, say'],
  ['SHOWER', 'Quick wash — or a brief spell of rain'],
  ['CURTAINS', 'Drawn at night'],
  ['SPANNER', 'Tool thrown in the works'],
  ['EASEL', 'Artist’s stand'],
  ['PAINT', 'Emulsion or gloss'],
  ['ANORAK', 'Hooded waterproof — or a trainspotter'],
  ['SANDALS', 'Strappy summer shoes'],
  ['TRAINERS', 'Running shoes'],
  ['TIARA', 'Princess’s jewelled headpiece'],
  ['EARRING', 'Stud or hoop'],
  ['ANGEL', 'On top of the Christmas tree, sometimes'],
  ['TINSEL', 'Sparkly Christmas decoration'],
  ['SANTA', 'Father Christmas'],
  ['REINDEER', 'Rudolph, for one'],
  ['EASTER', 'Spring festival of chocolate eggs'],
  ['SAINT', 'George, of England'],
  ['TORTOISE', 'Beat the hare in the fable'],
  ['OTTER', 'Whiskered river swimmer'],
  ['SEAL', 'Sea mammal — or close an envelope'],
  ['PARROT', 'Talking bird'],
  ['EAGLE', 'Bird of prey — or two under par'],
  ['RAVEN', 'Black bird kept at the Tower of London'],
  ['ANTLER', 'Stag’s branch-like horn'],
  ['NETTLE', 'Stinging weed, soothed with a dock leaf'],
  ['THISTLE', 'Prickly emblem of Scotland'],
  ['LAVENDER', 'Purple plant that smells lovely'],
  ['STREAM', 'Small river — or watch online'],
  ['COAST', 'Where land meets sea'],
  ['SEASIDE', 'Where to buy a stick of rock'],
  ['CATHEDRAL', 'St Paul’s, for one'],
  ['PALACE', 'Buckingham, for one'],
  ['STATION', 'Where trains stop'],
  ['TRACTOR', 'Farm vehicle'],
  ['TRAILER', 'Film preview — or towed behind a car'],
  ['ATLAS', 'Book of maps'],
  ['TENT', 'Pitched at a festival'],
  ['HOTEL', 'Rooms, a reception and a minibar'],
  ['SAILOR', 'Seafarer'],
  ['OAR', 'Rowing blade'],
  ['NURSE', 'Hospital carer'],
  ['DENTIST', 'Gives your teeth a check-up'],
  ['SOLDIER', 'Army member — or a toast finger for an egg'],
  ['ARTIST', 'Painter, perhaps'],
  ['TRIVIA', 'Pub quiz facts'],
  ['SEASON', 'Spring, summer, autumn or winter'],
  ['SUNSET', 'When the sun goes down'],
  ['TENNER', 'Ten-pound note'],
  ['TROLLEY', 'Wheeled supermarket basket'],
  ['LOTTERY', 'Weekly draw for millions'],
  ['ROULETTE', 'Casino wheel game'],
  ['CHEERS', 'Said with glasses raised'],
  ['SNORE', 'Noisy night-time breathing'],
  ['SNEEZE', 'Achoo!'],
  ['ROMANCE', 'Hearts and flowers'],
  ['HONEYMOON', 'Trip just after the wedding'],
  ['VALENTINE', 'Your date on 14 February'],
  ['ELOPE', 'Run off to marry in secret'],
  ['ALTAR', 'Where the couple stand in church'],
  ['BRIDE', 'She walks down the aisle'],
  ['CONFETTI', 'Thrown over the newlyweds'],
  ['PARTNER', 'Other half'],
  ['DARLING', 'Term of endearment'],
]
